services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: copilot
      POSTGRES_PASSWORD: copilot
      POSTGRES_DB: copilot_sui
    ports:
      - "5432:5432"
    volumes:
      - volum_postgres:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  server-copilot:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - CORS_ORIGINI=http://localhost:5173,http://localhost:3000
      - SUI_RPC_URL=https://fullnode.testnet.sui.io:443
      - SUI_RETEA=testnet
      - LLM_URL=http://host.docker.internal:11434
      - LLM_MODEL=llama3.1:8b-instruct
      - CHEIE_API_SERVER=schimba-ma
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://copilot:copilot@postgres:5432/copilot_sui
    depends_on:
      - postgres
      - redis

volumes:
  volum_postgres:
